### ISSUE TITLE
Graphical artificats across all supported games.

### ISSUE THREAD

**Issue by AnotherPocket** [obsidian-dot-dev/openFPGA-AtariSystem1#1]
Hello. Thank you for this new core. I found graphical artifact across all supported games. I double checked the files to make sure they are good and that they work on other emulators. Indian Jones is a good example, it's not very playable in its current state. I am assuming this is due to this core being new and hopefully I am not coming across as complaining. Thank you!

**Comment by Eddie6628** [comment]
I have the same issue. I tried another SD card with just this core. I have a newer pocket  late 2023. I really appreciate your work!!

**Comment by obsidian-dot-dev** [comment]
Thanks for reporting.  Yes, this is an issue I'm aware of, and have been trying to fix for a couple of weeks.  For some reason, the older-rev pockets are much less sensitive to SDRAM timing parameters -- but given that all of the crucial componenets are the same between revisions, it's not clear what the critical difference is.

Unfortunately, at this point I'm not sure what else to try to fix the issue, and none of my pockets exhibit this behavior, so I can't give an ETA for when I might get this fixed. 

So far, I've tried many different things, including:
- Move from fractional to integer clocks.
- Apply timing constraints for the SDRAM clock.
- Switch to CAS3 memory latency.
- Reduce SDRAM clock speed.
- Setting "fast" IO attributes on sdram pins.

None of which seem to have a material impact on the core behavior for impacted users - and the core still functions for me otherwise.

**Comment by AnotherPocket** [comment]
My Pocket is from late 2023, it is the translucent green from the limited run. Thank you for responding. If you have any ideas or files you would like tested, please let me know. I'd love to see this working across all hardware releases. I appreciate your hard work. You have already given me a lot of great experiences on my Pocket!

**Comment by obsidian-dot-dev** [comment]
Should be fixed in release v0.9.1 - let me know if the issue persists.

**Comment by AnotherPocket** [comment]
That fixed it. Thank you very much!
